<?php

Class ActiviteInscriptionCreneau extends Model {
    var $table='INSCRIPTION INNER JOIN ACTIVITE ON ACTIVITE.ID_ACTIVITE = INSCRIPTION.ID_ACTIVITE INNER JOIN CRENEAU on ACTIVITE.ID_ACTIVITE = CRENEAU.ID_ACTIVITE AND INSCRIPTION.CRENEAU = CRENEAU.NUM_CRENEAU
    INNER JOIN ADHERENT ON ACTIVITE.ID_LEADER = ADHERENT.ID_ADHERENT';

}
