<?php

class ActiviteParticipantsAdherent extends Model {
    //put your code here
    /*var $table = 'CRENEAU
    LEFT JOIN INSCRIPTION on INSCRIPTION.CRENEAU = CRENEAU.NUM_CRENEAU
AND INSCRIPTION.ID_ACTIVITE = CRENEAU.ID_ACTIVITE
LEFT JOIN ADHERENT ON ADHERENT.ID_ADHERENT = INSCRIPTION. ID_ADHERENT
LEFT JOIN LISTE_INVITES on LISTE_INVITES.ID_INSCRIPTION = INSCRIPTION.ID
LEFT JOIN INVITE on LISTE_INVITES.ID_INVITE = INVITE.ID_PERS_EXTERIEUR';*
   */
    var $table
        = 'CRENEAU c
LEFT JOIN INSCRIPTION i on c.NUM_CRENEAU = i.CRENEAU AND c.ID_ACTIVITE = i.ID_ACTIVITE
LEFT JOIN ADHERENT a on i.ID_ADHERENT = a.ID_ADHERENT
LEFT JOIN LISTE_INVITES li on i.ID = li.ID_INSCRIPTION
LEFT JOIN INVITE inv on inv.ID_PERS_EXTERIEUR = li.ID_INVITE';
}