<?php

class ActiviteParticipantsLeader extends Model {
    //put your code here
    var $table = 'INSCRIPTION INNER JOIN ADHERENT ON INSCRIPTION.ID_ADHERENT = ADHERENT.ID_ADHERENT
INNER JOIN CRENEAU ON INSCRIPTION.CRENEAU = CRENEAU.NUM_CRENEAU AND INSCRIPTION.ID_ACTIVITE = CRENEAU.ID_ACTIVITE
LEFT OUTER JOIN LISTE_INVITES ON INSCRIPTION.ID = LISTE_INVITES.ID_INSCRIPTION
LEFT OUTER JOIN INVITE ON INVITE.ID_PERS_EXTERIEUR = LISTE_INVITES.ID_INVITE';
}