//passage en datetime
ALTER TABLE `inscription` 
CHANGE `DATE_INSCRIPTION` `DATE_INSCRIPTION` DATETIME NOT NULL, 
CHANGE `DATE_PAIEMENT` `DATE_PAIEMENT` DATETIME 
on update CURRENT_TIMESTAMP DEFAULT NULL;